//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.CARTs = new HashSet<CART>();
        }
    
        public string ID { get; set; }
        public string GUEST { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public string BILL_STATUS { get; set; }
        public Nullable<bool> IS_APPROVED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
        public virtual GUEST_INFO GUEST_INFO { get; set; }
    }
}
