//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WISHLIST
    {
        public int ID { get; set; }
        public string PRODUCT { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<int> PRICE { get; set; }
    }
}
